blank_issues_enabled: true
contact_links:
  - name: "‚ùì Question"
    url: https://github.com/seroperson/jvm-live-reload/discussions/new
    about:
      "This issue tracker is not for questions. Please ask a question using
      GitHub Discussions"
